local Kavo = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local UI = Kavo.CreateLib("Script Loader", "DarkTheme")

local Cheats = UI:NewTab("Читы")
local CheatsSec = Cheats:NewSection("Игровые читы")
CheatsSec:NewButton("Dead Rails", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/maximum-arc/main/main/scripts/dead_rails.lua"))()
end)
CheatsSec:NewButton("Doors", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/maximum-arc/main/main/scripts/doors.lua"))()
end)
CheatsSec:NewButton("Underground War 2", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/maximum-arc/main/main/scripts/undegroundwar2.lua"))()
end)

local Utils = UI:NewTab("Утилиты")
local UtilsSec = Utils:NewSection("Полезные скрипты")
UtilsSec:NewButton("NPC Aim Assist", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/maximum-arc/main/main/scripts/NPC_aim.lua"))()
end)
